import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from './components/shared/Navbar';
import Footer from './components/shared/Footer';
import AuthProvider from '@/services/AuthProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Car App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="doctortheme">
      <AuthProvider>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
      </AuthProvider>
    </html>
  );
}
